name = "base-api"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-01-02"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "tasks"
# ローカル用
database_id = DATABASE_ID

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1